FROM python:3.9-slim

# Update system packages
RUN apt-get update && apt-get upgrade -y && apt-get clean && rm -rf /var/lib/apt/lists/*

# Main app: web-api-service
WORKDIR /app/web-api-service
COPY web-api-service/. .
RUN pip install --no-cache-dir -r requirements.txt

# Dependency: cvm-attestation
WORKDIR /app/cvm-attestation
COPY cvm-attestation/. .

# Expose port
EXPOSE 5000

# Run the application
WORKDIR /app/web-api-service
CMD ["python", "app.py"]
#CMD ["python", "-c", "import app; app.app.run(host='0.0.0.0', port=5000, debug=False)"]