apiVersion: apps/v1
kind: Deployment
metadata:
  name: pygentvm-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pygentvm-containers
  template:
    metadata:
      labels:
        app: pygentvm-containers
    spec:
      containers:
      - name: pygentvm-container
        image: gnkdev.azurecr.io/python-web-api-slim
        imagePullPolicy: Always
        ports:
        - containerPort: 50052
        securityContext:
          privileged: true
          capabilities:
            add:
            - SYS_ADMIN
        volumeMounts:
        - mountPath: /sys/kernel/security
          name: security-volume
      volumes:
      - name: security-volume
        hostPath:
          path: /sys/kernel/security
          type: Directory
      nodeSelector:
        agentpool: tlpool
---
apiVersion: v1
kind: Service
metadata:
  name: pygentvm-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 50061
    targetPort: 5000
  selector:
    app: pygentvm-containers