apiVersion: apps/v1
kind: Deployment
metadata:
  name: pygencvm2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pygencvm2-containers
  template:
    metadata:
      labels:
        app: pygencvm2-containers
    spec:
      containers:
      - name: pygencvm2-container
        image: gnkdev.azurecr.io/pygentvmcvm
        imagePullPolicy: Always
        ports:
        - containerPort: 50052
        securityContext:
          privileged: true
          capabilities:
            add:
            - SYS_ADMIN
        volumeMounts:
        - mountPath: /sys/kernel/security
          name: security-volume
      volumes:
      - name: security-volume
        hostPath:
          path: /sys/kernel/security
          type: Directory
      nodeSelector:
        agentpool: amdcvmpool2
---
apiVersion: v1
kind: Service
metadata:
  name: pygencvm2-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 50070
    targetPort: 5000
  selector:
    app: pygencvm2-containers